import { type TeamRow } from "@/components/home/Team/TeamClient";

export const FALLBACK_TEAM: TeamRow[] = [
  {
    id: "b361f844-8097-45e1-b34d-6973fb84d055",
    name: "Vaithiyanathan Sri Kesava Raman",
    role: "Advisory Council",
    image_url: "/team/kesava.png",
    linkedin_url: "https://www.linkedin.com/in/kesava-raman",
    group: "Advisory",
    display_order: 5,
  },
  {
    id: "c61e9060-ebfb-4e77-8041-e0599795d748",
    name: "En Hao Tew",
    role: "Advisory Council",
    image_url: "/team/En Hao.jpg",
    linkedin_url: "https://www.linkedin.com/in/en-hao-tew/",
    group: "Advisory",
    display_order: null,
  },
  {
    id: "3a2518c8-f038-49bd-8b37-d65e2b2af751",
    name: "Raymond Loong Ng",
    role: "Director & President",
    image_url: "/team/raymond.png",
    linkedin_url: "https://www.linkedin.com/in/raymond-loong-ng",
    group: "Board Members",
    display_order: 0,
  },
  {
    id: "5a98c73a-eae0-4265-9b13-563aa1f981b3",
    name: "Zaer",
    role: "Co-Founder",
    image_url: "/team/zaer.png",
    linkedin_url: "https://www.linkedin.com/in/zaerzaqy",
    group: "Board Members",
    display_order: 1,
  },
  {
    id: "c094a082-7186-4048-89dd-0c839ade8605",
    name: "Soh Hong Yu",
    role: "Vice President",
    image_url: "/team/hongyu.png",
    linkedin_url: "https://www.linkedin.com/in/soh-hong-yu-ultraraptor",
    group: "Board Members",
    display_order: 2,
  },
  {
    id: "2516f3ca-3bfe-484d-9926-7c6c90acf492",
    name: "Cleveland",
    role: "Co-Founder",
    image_url: "/team/cleveland.jpg",
    linkedin_url: "https://www.linkedin.com/in/cleverleverland",
    group: "Board Members",
    display_order: 3,
  },
  {
    id: "1338b465-0a84-4b00-8a7b-94ce0e569f53",
    name: "Xie Kaiwen",
    role: "Head of SYAI Inspire",
    image_url: "/team/kaiwen.png",
    linkedin_url: "https://www.linkedin.com/in/kaiwen-xie/",
    group: "Executive Committee",
    display_order: 1,
  },
  {
    id: "eba208a8-608b-4830-9cb1-8a80a961f899",
    name: "Soh Tze Aan",
    role: "Treasurer",
    image_url: "/team/Soh_Tze_Aan.JPG",
    linkedin_url: "https://www.linkedin.com/in/tzeaan",
    group: "Executive Committee",
    display_order: 2,
  },
  {
    id: "3989d0d2-d2ab-4f3c-9f6b-ad62d3d10ce9",
    name: "Kaleb Nim",
    role: "Head of SYAI Monthly Meetups",
    image_url: "/team/kaleb.png",
    linkedin_url: "https://www.linkedin.com/in/kaleb-nim",
    group: "Executive Committee",
    display_order: 4,
  },
  {
    id: "6f32d298-2eaa-4b16-b68d-c1fb4368f410",
    name: "Yovita Singh Jolly",
    role: "Secretary",
    image_url: "/team/Yovita_Singh_Jolly.jpg",
    linkedin_url: "https://www.linkedin.com/in/yovitasinghjolly",
    group: "Executive Committee",
    display_order: 5,
  },
  {
    id: "0c079e2e-39ae-4e22-9139-2434d57f2f0c",
    name: "Eric Law",
    role: "Head of SYAI External Relations",
    image_url: "/team/Eric_Law.jpg",
    linkedin_url: "https://www.linkedin.com/in/law-eric/",
    group: "Executive Committee",
    display_order: null,
  },
  {
    id: "a6c0081f-4227-407b-b25c-54a4f6ac8eb9",
    name: "Ho Sheng Xian Darwin",
    role: "Head of SYAI Strategic Growth",
    image_url: "/team/Darwin.jpg",
    linkedin_url: "https://www.linkedin.com/in/hoshengxiandarwin/",
    group: "Executive Committee",
    display_order: null,
  },
  {
    id: "a96cf29f-5272-4409-ae47-fa751ea404b6",
    name: "Ang Zi En Sherlyn",
    role: "Subcommittee member",
    image_url: "/team/Sherlyn_Ang.jpg",
    linkedin_url: "https://www.linkedin.com/in/sherlyn-ang-6b3812315",
    group: "Subcommittee",
    display_order: 0,
  },
  {
    id: "f73db404-0c9a-40a6-8762-3057d3968dd6",
    name: "Beth Anne Teo",
    role: "Subcommittee member",
    image_url: "/team/Beth_Anne_Teo.PNG",
    linkedin_url: "https://www.linkedin.com/in/beth-a-9aa20329a",
    group: "Subcommittee",
    display_order: 2,
  },
  {
    id: "c14fb76d-2030-4c09-a3f9-8019306b7cb6",
    name: "Jaslyn Tan Xuan Ning",
    role: "Subcommittee",
    image_url: "/team/Jaslyn_Tan.jpg",
    linkedin_url: "https://www.linkedin.com/in/jaslyn-tan-1b5681356",
    group: "Subcommittee",
    display_order: 4,
  },
  {
    id: "dac1cfcd-aaa3-4b9b-9bcf-53b90672fb3d",
    name: "Cham Si Ao",
    role: "SYAI Inspire Subcommittee",
    image_url: "/team/Cham_Si_Ao.jpg",
    linkedin_url: "https://www.linkedin.com/in/si-ao-cham-920037213",
    group: "Subcommittee",
    display_order: 7,
  },
  {
    id: "157854f3-7531-469e-818d-a88e41b28d91",
    name: "Vijeyakumar Dakshaa",
    role: "Subcommittee member",
    image_url: "/team/Vijeyakumar_Dakshaa.PNG",
    linkedin_url: "https://www.linkedin.com/in/dakshaa-v",
    group: "Subcommittee",
    display_order: 8,
  },
  {
    id: "4a76cc42-7f2a-41a9-a6be-2b721a5d16e2",
    name: "Min Thet Khine",
    role: "Subcommittee member",
    image_url: "/team/Min_Thet_Khine.JPG",
    linkedin_url: "https://www.linkedin.com/in/min-thet-khine2005/",
    group: "Subcommittee",
    display_order: 9,
  },
  {
    id: "7db0a53a-0173-4794-9d5b-e7b8349a7d2b",
    name: "Yuriel Wang Jun Long Ryan",
    role: "Subcommittee member",
    image_url: "/team/Yuriel.jpeg",
    linkedin_url: "https://www.linkedin.com/in/yuriel-ryan/",
    group: "Subcommittee",
    display_order: 10,
  },
  {
    id: "867cc8c7-9b8f-4478-9276-d905782d2909",
    name: "Meressa Ng",
    role: "Subcommittee member",
    image_url: "/team/Meressa.jpg",
    linkedin_url: "http://linkedin.com/in/meressa-ng-83b108309",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "3fa270da-095b-4beb-b7da-a53fb4565815",
    name: "Chew Yee Jing",
    role: "Subcommittee member",
    image_url: "/team/Chew_Yee_Jing.jpg",
    linkedin_url: "https://www.linkedin.com/in/chew-y-b1bb3b239/",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "495fc0cd-1b6f-4cc8-8efa-a792bc9c0fc7",
    name: "Moiz Khambhati",
    role: "Subcommittee member",
    image_url: "/team/Moiz.jpg",
    linkedin_url: "linkedin.com/in/moiz-khambhati-3a66b9301",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "09b5e19a-f8be-4f78-b04d-58007403e9e3",
    name: "Zhou Jing Chun",
    role: "Subcommittee member",
    image_url: "/team/Jing Chun.jpg",
    linkedin_url: "https://www.linkedin.com/in/jingchun2004/",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "87aa4fd8-8be7-43a6-88f6-a7ac46b96747",
    name: "Saumil Anand",
    role: "Subcommittee member",
    image_url: "/team/Saumil.jpg",
    linkedin_url: "http://linkedin.com/in/saumil707",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "8f5cfd38-9298-44ec-bc50-0887b63fbf57",
    name: "Zhu Bolin",
    role: "Subcommittee member",
    image_url: "/team/zhu_bolin.jpg",
    linkedin_url: "http://linkedin.com/in/zhu-bolin-717790191",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "af370e2e-f35c-465b-a1fc-abd3138ca7ae",
    name: "Leo Edwards",
    role: "Subcommittee member",
    image_url: "/team/Leo Edwards.jpeg",
    linkedin_url: "https://www.linkedin.com/in/truegrand",
    group: "Subcommittee",
    display_order: null,
  },
  {
    id: "e687385d-52c6-4cd5-bd06-e818dff8abef",
    name: "Perynn Neo",
    role: "Subcommittee member",
    image_url: "/team/Perynn_Neo.jpg",
    linkedin_url: "https://www.linkedin.com/in/perynn-neo-377194314",
    group: "Subcommittee",
    display_order: null,
  },
];
